### ISSUE TITLE
<meta name="prerender-header" seems to be ignored

### ISSUE THREAD

**Issue by vzaidman** [sanfrancesco/prerendercloud-nodejs#20]

**Comment by jotto** [comment]
Can you send example code or URL where I can debug?

**Comment by vzaidman** [comment]
ok i figured out what happened there:
i had meta tag containing unencoded latters in hebrew:

```
<meta name="prerender-header" content="location: /something/something2/{HEBREW TEXT HERE}">
```

so the result from the prerender was 301 without the location and no warning or error anywhere.

now i just used urlEncode on it and it got fixed.

I'd suggest you to maybe add some sort of warning or error but if not, people can always find this bug instead.

Thanks!
